# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fsoc < Formula
  desc "Cisco FSO Platform Developer's Control Tool"
  homepage "https://github.com/cisco-open/fsoc"
  version "0.43.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.8/fsoc-darwin-arm64.tar.gz"
      sha256 "f95215152b4b11264f802efb3a89130f1ce92533db67316c533f3a96ae5ff7ba"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.8/fsoc-darwin-amd64.tar.gz"
      sha256 "16d952c0f93ef56d832012412ad7a46c1f262c36d223dab5e8f2aa86fe369acc"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.8/fsoc-linux-arm64.tar.gz"
      sha256 "6446c11a86b3fb8f233bf426f5d8bc7dd5eb8252b2313e05cf4d07b072f89c44"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.8/fsoc-linux-amd64.tar.gz"
      sha256 "f85158470135889caa7db4bbaf9f554012277c9de057defacc80b4e75b07d902"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  test do
    system "#{bin}/fsoc version"
  end
end
