# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fsoc < Formula
  desc ""
  homepage "https://github.com/cisco-open/fsoc"
  version "0.43.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.6/fsoc-darwin-arm64.tar.gz"
      sha256 "c5051117c5805c6724c2f28cac3ddddb9b4447add69f5fd418edc09ecbea08f0"

      def install
        bin.install "fsoc-darwin-arm64"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.6/fsoc-darwin-amd64.tar.gz"
      sha256 "fa387cb7c766297c4e22f4641f5dff2d034b735e3f3a124ccd3fd93cc66bccd8"

      def install
        bin.install "fsoc-darwin-amd64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.6/fsoc-linux-arm64.tar.gz"
      sha256 "96ac090924896fbc056cd5e99608e466d0e3ac0e988c9557d692c2a551ca56e0"

      def install
        bin.install "fsoc-linux-arm64"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.6/fsoc-linux-amd64.tar.gz"
      sha256 "c32d709059dd3998775103764c1d61230d783d410417c1f0ac620df64e70ae10"

      def install
        bin.install "fsoc-linux-amd64"
      end
    end
  end
end
