# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fsoc < Formula
  desc "Cisco FSO Platform Developer's Control Tool"
  homepage "https://github.com/cisco-open/fsoc"
  version "0.43.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.4/fsoc-darwin-arm64.tar.gz"
      sha256 "cb8ff74c1a7b0c66dbf21fb1516f1ce55949ee82bf1e1241cb71eb318fc4a8c2"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.4/fsoc-darwin-amd64.tar.gz"
      sha256 "fe37df1d47b2e91eb8ff365fcacf1e4193e7beced7e3a7ef6e83a249242d2d8e"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.4/fsoc-linux-amd64.tar.gz"
      sha256 "8b63efbad00e5d9496c68c5462b73023136ad92427f1a21aa7f47a567dbcd2d8"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.4/fsoc-linux-arm64.tar.gz"
      sha256 "ca1d06c24dbd3f40a1a97fdacd89e923f879ce8d01373e7da39cf90f1ea250a8"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  test do
    system "#{bin}/fsoc version"
  end
end
