# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fsoc < Formula
  desc "Cisco FSO Platform Developer's Control Tool"
  homepage "https://github.com/cisco-open/fsoc"
  version "0.43.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.3/fsoc-darwin-arm64.tar.gz"
      sha256 "4b8558b555aa29b802244af7b2de447a49f080bbde1f49cf46bd3b633bccf258"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.3/fsoc-darwin-amd64.tar.gz"
      sha256 "ae95753e2af14a35d59cd1f9363402624c4a371b8c8e77cba62eeae1f098d4bc"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.3/fsoc-linux-arm64.tar.gz"
      sha256 "1cab6d73f475edbcd597e04957d51430acb7176b54f817316edc1a280cd97463"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.3/fsoc-linux-amd64.tar.gz"
      sha256 "aafea0ae75027ca860aa012f764da3296bcbcd3c04d6f6deb10c26e18190ec4c"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  test do
    system "#{bin}/fsoc version"
  end
end
