# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fsoc < Formula
  desc "Cisco FSO Platform Developer's Control Tool"
  homepage "https://github.com/cisco-open/fsoc"
  version "0.43.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.3/fsoc-darwin-arm64.tar.gz"
      sha256 "b711735c6e7247557079d44f2e113f7fe32d5b7411b3001beb8573334517971e"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.3/fsoc-darwin-amd64.tar.gz"
      sha256 "3473b64c294be1c74a3f6a7328162a4647bab5af610c47837a49984209f05151"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.3/fsoc-linux-arm64.tar.gz"
      sha256 "ed65246366d5941abe8d73e96a6bfce902aa75de90cf1da9c2d8a1fc63eee1a5"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Neo2308/fsoc/releases/download/v0.43.3/fsoc-linux-amd64.tar.gz"
      sha256 "e850239f47fd0e3dd69ebfa7d44bfcd7301132616184a23452b7e83bc7f0fbc1"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  test do
    system "#{bin}/fsoc version"
  end
end
